# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true
org.gradle.configuration-cache = true

# Fabric Properties
loom_version = 1.18-SNAPSHOT

# Mod Data
name = Fluffy Isles
description = Adds small utility modifications for the Skyblock Isles server.
version = 0.0.1
group = pet.itpuppy.fluffyisles